---
driver:
  name: vagrant
  provider: vmware_fusion
  customize:
    memory: 2048
    cpus: 3


provisioner:
  name: chef_solo
  require_chef_omnibus: 12.10

platforms:
  - name: macosx-10.10
    driver:
      gui: true
      box: macosx-10.10

suites:
  - name: safari_test
    run_list:
      - safari_test::version
      - safari_test::extension
    attributes:
